# GitHub Actions for GEOS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>
# Based on AZP configuration by Mateusz Loskot <mateusz at loskot dot net>

name: 'CI'

on:
  push:
    paths-ignore:
      - 'web/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read  #  to fetch code (actions/checkout)

env:
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_COMPRESS: "true"
  CCACHE_COMPRESSLEVEL: "6"
  CCACHE_MAXSIZE: "300M"

jobs:
  linux:
    name: 'Linux'
    env:
      GEOS_INSTALL: ${{ github.workspace }}/inst
    strategy:
      fail-fast: false
      matrix:
        ci:
        - cxx_compiler: clang++-21
          c_compiler: clang-21
          build_type: Relase
          library_type: shared
          cxxstd: 20
          packages: clang-21
          os: ubuntu-26.04

        - cxx_compiler: clang++-22
          c_compiler: clang-22
          build_type: Relase
          library_type: static
          cxxstd: 20
          packages: clang-22
          os: ubuntu-26.04


    runs-on: ${{ matrix.ci.os }}
    steps:

    - name: 'Install Dependencies'
      run: |
        set -e
        sudo -E apt-get update
        sudo -E apt-get autopurge -y needrestart
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends install doxygen ccache ${{ matrix.ci.packages }}

    - uses: actions/checkout@v7.0.1

    - name: Retrieve build cache
      uses: actions/cache/restore@v6.1.0
      id: restore-cache
      with:
        path: .ccache
        key: ${{ matrix.ci.os }}-${{ matrix.ci.build_type}}-${{ matrix.ci.library_type }}-${{ matrix.ci.cxx_compiler }}-${{ matrix.ci.cxxstd }}-${{ github.ref_name }}-${{ github.run_id }}
        restore-keys: ${{ matrix.ci.os }}-${{ matrix.ci.build_type}}-${{ matrix.ci.library_type }}-${{ matrix.ci.cxx_compiler }}-${{ matrix.ci.cxxstd }}

    - name: 'Build'
      run: |
        set -e
        which cmake
        cmake --version
        cmake --log-level VERBOSE ${{ matrix.ci.cmake_extra }} \
          -D CMAKE_BUILD_TYPE=${{ matrix.ci.build_type }} \
          -D BUILD_SHARED_LIBS=${{ matrix.ci.library_type == 'shared' && 'ON' || 'OFF' }} \
          -D CMAKE_C_COMPILER=${{ matrix.ci.c_compiler }} \
          -D CMAKE_CXX_COMPILER=${{ matrix.ci.cxx_compiler }} \
          -D CMAKE_CXX_STANDARD=${{ matrix.ci.cxxstd }} \
          -D CMAKE_INSTALL_PREFIX=$GEOS_INSTALL \
          -D USE_CCACHE=ON \
          -S . -B build
        cmake --build build -j $(nproc)
        cmake --build build --target docs
        ccache --show-stats

    - name: Save build cache
      uses: actions/cache/save@v6.1.0
      with:
        path: .ccache
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}

    - name: Test
      working-directory: ./build
      run: ctest --output-on-failure

    - name: Install
      run: cmake --install build

  macos:
    name: 'macOS clang'
    env:
      GEOS_INSTALL: ${{ github.workspace }}/inst
    strategy:
      fail-fast: false
      matrix:
        include:
        - xcode: "26.6"
          cxxstd: 26
          build_type: Release
          library_type: shared
          runs_on: macos-26-intel

    runs-on: ${{ matrix.runs_on }}
    steps:

    - name: 'Setup'
      run: brew install ccache

    - name: 'Install'
      env:
        XCODE_APP: /Applications/XCode_${{ matrix.xcode }}.app
      run: |
        set -e
        uname -a
        sudo xcode-select -switch ${XCODE_APP}
        which clang++
        clang++ --version

    - uses: actions/checkout@v7.0.1

    - name: Retrieve build cache
      uses: actions/cache/restore@v6.1.0
      id: restore-cache
      with:
        path: .ccache
        key: ${{ runner.os }}-${{ matrix.xcode }}-${{ matrix.build_type}}-${{ matrix.library_type}}-${{ matrix.cxxstd }}-${{ github.ref_name }}-${{ github.run_id }}
        restore-keys: ${{ runner.os }}-${{ matrix.xcode }}-${{ matrix.build_type}}-${{ matrix.library_type}}-${{ matrix.cxxstd }}

    - name: 'Build'
      run: |
        set -e
        cmake --log-level VERBOSE \
          -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -D BUILD_SHARED_LIBS=${{ matrix.library_type == 'shared' && 'ON' || 'OFF' }} \
          -D CMAKE_INSTALL_PREFIX=$GEOS_INSTALL \
          -D CMAKE_CXX_STANDARD=${{ matrix.cxxstd }} \
          -D USE_CCACHE=ON \
          -S . -B build
        cmake --build build --config ${{ matrix.build_type }} -j 4
        ccache --show-stats

    - name: Save build cache
      uses: actions/cache/save@v6.1.0
      with:
        path: .ccache
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}

    - name: 'Test'
      working-directory: ./build
      run: ctest --output-on-failure -C ${{ matrix.build_type }}

    - name: Install
      run: cmake --install build --config ${{ matrix.build_type }}

  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1

    - name: Retrieve build cache
      uses: actions/cache/restore@v6.1.0
      id: restore-cache
      with:
        path: .ccache
        key: freebsd-${{ github.ref_name }}-${{ github.run_id }}
        restore-keys: freebsd

    - name: Build, test, install
      uses: vmactions/freebsd-vm@v1.5.5
      with:
        release: "15.0"
        envs: CCACHE_COMPRESS CCACHE_COMPRESSLEVEL CCACHE_MAXSIZE
        usesh: true
        prepare: |
          pkg install -y cmake ccache
        run: |
          set -e
          export CCACHE_DIR=$PWD/.ccache
          cmake --log-level VERBOSE \
            -D CMAKE_INSTALL_PREFIX=/tmp/inst \
            -D USE_CCACHE=ON \
            -S . -B build
          cmake --build build -j $(nproc)
          ccache --show-stats
          ctest --test-dir build --output-on-failure
          cmake --install build
          rm -rf build
          rm -rf /tmp/inst

    - name: Save build cache
      uses: actions/cache/save@v6.1.0
      with:
        path: .ccache
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}

