# GitHub Actions for GEOS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>
# Based on AZP configuration by Mateusz Loskot <mateusz at loskot dot net>

name: 'CI'

on:
  push:
    paths-ignore:
      - 'web/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read  #  to fetch code (actions/checkout)

env:
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_COMPRESS: "true"
  CCACHE_COMPRESSLEVEL: "6"
  CCACHE_MAXSIZE: "300M"

jobs:
  windows-msvc-msbuild:
    name: Windows (MSVC MSBuild)
    runs-on: windows-2022
    steps:
    - name: 'Check Out'
      uses: actions/checkout@v4

    # ccache not supported for this generator and/or Debug

    - name: 'Build'
      shell: cmd
      run: |
        md build
        cd build
        cmake --version
        cmake ^
          -G "Visual Studio 17 2022" ^
          -D CMAKE_BUILD_TYPE=Debug ^
          -D CMAKE_CXX_STANDARD=14 ^
          -D BUILD_SHARED_LIBS=ON ^
          ..
        IF %ERRORLEVEL% NEQ 0 exit
        cmake --build . --config Debug -j 4 -- /p:CL_MPcount=4

    - name: 'Test'
      working-directory: build
      run: ctest --output-on-failure -C Debug

  windows-msvc-ninja:
    name: Windows (MSVC Ninja)
    runs-on: windows-2019
    steps:
    - name: 'Check Out'
      uses: actions/checkout@v4

    - name: 'Setup'
      run: choco install ccache ninja

    - name: Retrieve build cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: .ccache
        key: windows-msvc-ninja-windows-2022-${{ github.ref_name }}-${{ github.run_id }}
        restore-keys: windows-msvc-ninja-windows-2022

    - name: 'Build'
      env:
        CCACHE_DIR: ${{ github.workspace }}\.ccache
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        md build
        cd build
        cmake --version
        cmake ^
          -G Ninja ^
          -D CMAKE_BUILD_TYPE=Release ^
          -D CMAKE_CXX_STANDARD=14 ^
          -D CMAKE_CXX_FLAGS=/W3 ^
          -D BUILD_SHARED_LIBS=ON ^
          -D USE_CCACHE=ON ^
          ..
        IF %ERRORLEVEL% NEQ 0 exit
        cmake --build . --config Release -j 4
        IF %ERRORLEVEL% NEQ 0 exit
        ccache --show-stats --verbose

    - name: Save build cache
      uses: actions/cache/save@v4
      with:
        path: .ccache
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}

    - name: 'Test'
      working-directory: build
      run: ctest --output-on-failure -C Release

